### ISSUE TITLE
VMs sometimes fail to launch

### ISSUE THREAD

**Issue by Lukasa** [projectcalico/calico-chef#1]
For some reason, after installing with Chef the openstack deployment sometimes fails to launch VMs. This can be resolved by restarting libvirtd on the compute hosts. This is quite confusing, as our install scripts restart libvirtd as the last action they take, so why another, later restart solves the problem is unclear. Some kind of timing window, I suspect.

**Comment by tomdee** [comment]
Closing v. old issue.
